app:
  userAgent: HeliontAgent
  referrer: https://example.com

indexing-settings:
  sites:
    - url: https://nikoartgallery.com/
      name: nikoartgallery
    - url: https://ipfran.ru/
      name: ipfran
    - url: https://svetlovka.ru/
      name: svetlovka

server:
  port: 8080

spring:
  datasource:
    username: root
    password: skc888@X
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterSetResults=utf8mb4
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true