app:
  userAgent: HeliontAgent
  referrer: https://example.com

indexing-settings:
  sites:
    - url: https://www.volochek.life/
      name: volochek
    - url: https://www.svetlovka.ru/
      name: svetlovka
    - url: https://www.playback.ru/
      name: playback
    - url: https://www.sendel.ru/
      name: sendel

server:
  port: 8080

spring:
  datasource:
    username: root
    password: skc888@X
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true